import {StyleSheet} from 'react-native'
export const styles = StyleSheet.create({
    Container:{
        backgroundColor:'#fff',
        margin:10,
        height:400,
        padding:10,
    },
    Card:{
        flexDirection:'row',
    },
    Text:{
        color:'#cd1817',
        fontWeight:'bold',
        fontSize:20,
        height:40,
        width:230,
        textAlign:'left',
        padding:5,
    },
    Container2:{
        width:'50%',
        paddingLeft:10,
        marginTop:10,
        height:300,
    },
    images:{
        width:160,
        height:170
    },
    installment:{
        bottom:50,
        width:80,
        height:20,
        color:'#fff',
        borderRadius:5,
        textAlign:'center',
        backgroundColor:'#FF8000'
    },
    nameProduct:{
        fontSize:15,
        fontWeight:'bold',
        color:'#424242',
        bottom:25
    },
    prices:{
        bottom:10,
        fontWeight:'bold',
        width:100,
        height:20,
        color:'#fff',
        borderRadius:10,
        textAlign:'center',
        backgroundColor:'#cd1817'
    },
    lucky:{
        bottom:40,
        width:125,
        height:20,
        color:'#fff',
        borderRadius:5,
        textAlign:'center',
        backgroundColor:'#cd1817'
    },
    discount:{
        textDecorationLine:'line-through',
        color:'#585858',
    }
})
